// Generated by CoffeeScript 1.6.3
(function() {
  require(__dirname + '/live-test');

  require(__dirname + '/misc-test');

  require(__dirname + '/queries-test');

  require(__dirname + '/nested-test');

  require(__dirname + '/sort-test');

}).call(this);
